version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ttt
      POSTGRES_USER: ttt
      POSTGRES_PASSWORD: ttt
  app:
    build: .
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/ttt
      SPRING_DATASOURCE_USERNAME: ttt
      SPRING_DATASOURCE_PASSWORD: ttt
    depends_on:
      - db